# Generated by Django 4.2.3 on 2023-11-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evill', '0004_alter_contact_data_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_data',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
