# Generated by Django 4.2.3 on 2023-11-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evill', '0005_alter_contact_data_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_data',
        ),
    ]
